export enum ErrorType {
  // 欄位驗證
  EMAIL_REQUIRED = "EMAIL_REQUIRED",
  EMAIL_INVALID = "EMAIL_INVALID",
  PASSWORD_REQUIRED = "PASSWORD_REQUIRED",

  // 資源不存在
  USER_NOT_FOUND = "USER_NOT_FOUND",

  // 權限
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",

  // 業務邏輯
  EMAIL_IN_USE = "EMAIL_IN_USE",

  // 報名
  SESSION_NOT_FOUND = "SESSION_NOT_FOUND",
  SESSION_FULL = "SESSION_FULL",
  SESSION_REQUIRED = "SESSION_REQUIRED",
}
