/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports all enum related types from the schema.
 *
 * 🟢 You can import this file directly.
 */

export const OAuthProviderType = {
  GOOGLE: "GOOGLE",
  LINE: "LINE",
} as const

export type OAuthProviderType =
  (typeof OAuthProviderType)[keyof typeof OAuthProviderType]

export const GenderType = {
  MALE: "MALE",
  FEMALE: "FEMALE",
  OTHER: "OTHER",
} as const

export type GenderType = (typeof GenderType)[keyof typeof GenderType]

export const RegistrationStatus = {
  PENDING: "PENDING",
  PAID: "PAID",
  FAILED: "FAILED",
} as const

export type RegistrationStatus =
  (typeof RegistrationStatus)[keyof typeof RegistrationStatus]
