/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `RegistrationSession` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model RegistrationSession
 *
 */
export type RegistrationSessionModel =
  runtime.Types.Result.DefaultSelection<Prisma.$RegistrationSessionPayload>

export type AggregateRegistrationSession = {
  _count: RegistrationSessionCountAggregateOutputType | null
  _min: RegistrationSessionMinAggregateOutputType | null
  _max: RegistrationSessionMaxAggregateOutputType | null
}

export type RegistrationSessionMinAggregateOutputType = {
  id: string | null
  registrationId: string | null
  sessionId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type RegistrationSessionMaxAggregateOutputType = {
  id: string | null
  registrationId: string | null
  sessionId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type RegistrationSessionCountAggregateOutputType = {
  id: number
  registrationId: number
  sessionId: number
  createdAt: number
  updatedAt: number
  _all: number
}

export type RegistrationSessionMinAggregateInputType = {
  id?: true
  registrationId?: true
  sessionId?: true
  createdAt?: true
  updatedAt?: true
}

export type RegistrationSessionMaxAggregateInputType = {
  id?: true
  registrationId?: true
  sessionId?: true
  createdAt?: true
  updatedAt?: true
}

export type RegistrationSessionCountAggregateInputType = {
  id?: true
  registrationId?: true
  sessionId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type RegistrationSessionAggregateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which RegistrationSession to aggregate.
   */
  where?: Prisma.RegistrationSessionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of RegistrationSessions to fetch.
   */
  orderBy?:
    | Prisma.RegistrationSessionOrderByWithRelationInput
    | Prisma.RegistrationSessionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the start position
   */
  cursor?: Prisma.RegistrationSessionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` RegistrationSessions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` RegistrationSessions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Count returned RegistrationSessions
   **/
  _count?: true | RegistrationSessionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the minimum value
   **/
  _min?: RegistrationSessionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the maximum value
   **/
  _max?: RegistrationSessionMaxAggregateInputType
}

export type GetRegistrationSessionAggregateType<
  T extends RegistrationSessionAggregateArgs,
> = {
  [P in keyof T & keyof AggregateRegistrationSession]: P extends
    | "_count"
    | "count"
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateRegistrationSession[P]>
    : Prisma.GetScalarType<T[P], AggregateRegistrationSession[P]>
}

export type RegistrationSessionGroupByArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.RegistrationSessionWhereInput
  orderBy?:
    | Prisma.RegistrationSessionOrderByWithAggregationInput
    | Prisma.RegistrationSessionOrderByWithAggregationInput[]
  by:
    | Prisma.RegistrationSessionScalarFieldEnum[]
    | Prisma.RegistrationSessionScalarFieldEnum
  having?: Prisma.RegistrationSessionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: RegistrationSessionCountAggregateInputType | true
  _min?: RegistrationSessionMinAggregateInputType
  _max?: RegistrationSessionMaxAggregateInputType
}

export type RegistrationSessionGroupByOutputType = {
  id: string
  registrationId: string
  sessionId: string
  createdAt: Date
  updatedAt: Date
  _count: RegistrationSessionCountAggregateOutputType | null
  _min: RegistrationSessionMinAggregateOutputType | null
  _max: RegistrationSessionMaxAggregateOutputType | null
}

export type GetRegistrationSessionGroupByPayload<
  T extends RegistrationSessionGroupByArgs,
> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<RegistrationSessionGroupByOutputType, T["by"]> & {
      [P in keyof T &
        keyof RegistrationSessionGroupByOutputType]: P extends "_count"
        ? T[P] extends boolean
          ? number
          : Prisma.GetScalarType<T[P], RegistrationSessionGroupByOutputType[P]>
        : Prisma.GetScalarType<T[P], RegistrationSessionGroupByOutputType[P]>
    }
  >
>

export type RegistrationSessionWhereInput = {
  AND?:
    | Prisma.RegistrationSessionWhereInput
    | Prisma.RegistrationSessionWhereInput[]
  OR?: Prisma.RegistrationSessionWhereInput[]
  NOT?:
    | Prisma.RegistrationSessionWhereInput
    | Prisma.RegistrationSessionWhereInput[]
  id?: Prisma.StringFilter<"RegistrationSession"> | string
  registrationId?: Prisma.StringFilter<"RegistrationSession"> | string
  sessionId?: Prisma.StringFilter<"RegistrationSession"> | string
  createdAt?: Prisma.DateTimeFilter<"RegistrationSession"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"RegistrationSession"> | Date | string
  registration?: Prisma.XOR<
    Prisma.RegistrationScalarRelationFilter,
    Prisma.RegistrationWhereInput
  >
  session?: Prisma.XOR<
    Prisma.SessionScalarRelationFilter,
    Prisma.SessionWhereInput
  >
}

export type RegistrationSessionOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  registrationId?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  registration?: Prisma.RegistrationOrderByWithRelationInput
  session?: Prisma.SessionOrderByWithRelationInput
}

export type RegistrationSessionWhereUniqueInput = Prisma.AtLeast<
  {
    id?: string
    registrationId_sessionId?: Prisma.RegistrationSessionRegistrationIdSessionIdCompoundUniqueInput
    AND?:
      | Prisma.RegistrationSessionWhereInput
      | Prisma.RegistrationSessionWhereInput[]
    OR?: Prisma.RegistrationSessionWhereInput[]
    NOT?:
      | Prisma.RegistrationSessionWhereInput
      | Prisma.RegistrationSessionWhereInput[]
    registrationId?: Prisma.StringFilter<"RegistrationSession"> | string
    sessionId?: Prisma.StringFilter<"RegistrationSession"> | string
    createdAt?: Prisma.DateTimeFilter<"RegistrationSession"> | Date | string
    updatedAt?: Prisma.DateTimeFilter<"RegistrationSession"> | Date | string
    registration?: Prisma.XOR<
      Prisma.RegistrationScalarRelationFilter,
      Prisma.RegistrationWhereInput
    >
    session?: Prisma.XOR<
      Prisma.SessionScalarRelationFilter,
      Prisma.SessionWhereInput
    >
  },
  "id" | "registrationId_sessionId"
>

export type RegistrationSessionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  registrationId?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.RegistrationSessionCountOrderByAggregateInput
  _max?: Prisma.RegistrationSessionMaxOrderByAggregateInput
  _min?: Prisma.RegistrationSessionMinOrderByAggregateInput
}

export type RegistrationSessionScalarWhereWithAggregatesInput = {
  AND?:
    | Prisma.RegistrationSessionScalarWhereWithAggregatesInput
    | Prisma.RegistrationSessionScalarWhereWithAggregatesInput[]
  OR?: Prisma.RegistrationSessionScalarWhereWithAggregatesInput[]
  NOT?:
    | Prisma.RegistrationSessionScalarWhereWithAggregatesInput
    | Prisma.RegistrationSessionScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"RegistrationSession"> | string
  registrationId?:
    | Prisma.StringWithAggregatesFilter<"RegistrationSession">
    | string
  sessionId?: Prisma.StringWithAggregatesFilter<"RegistrationSession"> | string
  createdAt?:
    | Prisma.DateTimeWithAggregatesFilter<"RegistrationSession">
    | Date
    | string
  updatedAt?:
    | Prisma.DateTimeWithAggregatesFilter<"RegistrationSession">
    | Date
    | string
}

export type RegistrationSessionCreateInput = {
  id: string
  createdAt?: Date | string
  updatedAt?: Date | string
  registration: Prisma.RegistrationCreateNestedOneWithoutRegistrationSessionsInput
  session: Prisma.SessionCreateNestedOneWithoutRegistrationSessionsInput
}

export type RegistrationSessionUncheckedCreateInput = {
  id: string
  registrationId: string
  sessionId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type RegistrationSessionUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  registration?: Prisma.RegistrationUpdateOneRequiredWithoutRegistrationSessionsNestedInput
  session?: Prisma.SessionUpdateOneRequiredWithoutRegistrationSessionsNestedInput
}

export type RegistrationSessionUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  registrationId?: Prisma.StringFieldUpdateOperationsInput | string
  sessionId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RegistrationSessionCreateManyInput = {
  id: string
  registrationId: string
  sessionId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type RegistrationSessionUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RegistrationSessionUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  registrationId?: Prisma.StringFieldUpdateOperationsInput | string
  sessionId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RegistrationSessionListRelationFilter = {
  every?: Prisma.RegistrationSessionWhereInput
  some?: Prisma.RegistrationSessionWhereInput
  none?: Prisma.RegistrationSessionWhereInput
}

export type RegistrationSessionOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type RegistrationSessionRegistrationIdSessionIdCompoundUniqueInput = {
  registrationId: string
  sessionId: string
}

export type RegistrationSessionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  registrationId?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type RegistrationSessionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  registrationId?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type RegistrationSessionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  registrationId?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type RegistrationSessionCreateNestedManyWithoutSessionInput = {
  create?:
    | Prisma.XOR<
        Prisma.RegistrationSessionCreateWithoutSessionInput,
        Prisma.RegistrationSessionUncheckedCreateWithoutSessionInput
      >
    | Prisma.RegistrationSessionCreateWithoutSessionInput[]
    | Prisma.RegistrationSessionUncheckedCreateWithoutSessionInput[]
  connectOrCreate?:
    | Prisma.RegistrationSessionCreateOrConnectWithoutSessionInput
    | Prisma.RegistrationSessionCreateOrConnectWithoutSessionInput[]
  createMany?: Prisma.RegistrationSessionCreateManySessionInputEnvelope
  connect?:
    | Prisma.RegistrationSessionWhereUniqueInput
    | Prisma.RegistrationSessionWhereUniqueInput[]
}

export type RegistrationSessionUncheckedCreateNestedManyWithoutSessionInput = {
  create?:
    | Prisma.XOR<
        Prisma.RegistrationSessionCreateWithoutSessionInput,
        Prisma.RegistrationSessionUncheckedCreateWithoutSessionInput
      >
    | Prisma.RegistrationSessionCreateWithoutSessionInput[]
    | Prisma.RegistrationSessionUncheckedCreateWithoutSessionInput[]
  connectOrCreate?:
    | Prisma.RegistrationSessionCreateOrConnectWithoutSessionInput
    | Prisma.RegistrationSessionCreateOrConnectWithoutSessionInput[]
  createMany?: Prisma.RegistrationSessionCreateManySessionInputEnvelope
  connect?:
    | Prisma.RegistrationSessionWhereUniqueInput
    | Prisma.RegistrationSessionWhereUniqueInput[]
}

export type RegistrationSessionUpdateManyWithoutSessionNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.RegistrationSessionCreateWithoutSessionInput,
        Prisma.RegistrationSessionUncheckedCreateWithoutSessionInput
      >
    | Prisma.RegistrationSessionCreateWithoutSessionInput[]
    | Prisma.RegistrationSessionUncheckedCreateWithoutSessionInput[]
  connectOrCreate?:
    | Prisma.RegistrationSessionCreateOrConnectWithoutSessionInput
    | Prisma.RegistrationSessionCreateOrConnectWithoutSessionInput[]
  upsert?:
    | Prisma.RegistrationSessionUpsertWithWhereUniqueWithoutSessionInput
    | Prisma.RegistrationSessionUpsertWithWhereUniqueWithoutSessionInput[]
  createMany?: Prisma.RegistrationSessionCreateManySessionInputEnvelope
  set?:
    | Prisma.RegistrationSessionWhereUniqueInput
    | Prisma.RegistrationSessionWhereUniqueInput[]
  disconnect?:
    | Prisma.RegistrationSessionWhereUniqueInput
    | Prisma.RegistrationSessionWhereUniqueInput[]
  delete?:
    | Prisma.RegistrationSessionWhereUniqueInput
    | Prisma.RegistrationSessionWhereUniqueInput[]
  connect?:
    | Prisma.RegistrationSessionWhereUniqueInput
    | Prisma.RegistrationSessionWhereUniqueInput[]
  update?:
    | Prisma.RegistrationSessionUpdateWithWhereUniqueWithoutSessionInput
    | Prisma.RegistrationSessionUpdateWithWhereUniqueWithoutSessionInput[]
  updateMany?:
    | Prisma.RegistrationSessionUpdateManyWithWhereWithoutSessionInput
    | Prisma.RegistrationSessionUpdateManyWithWhereWithoutSessionInput[]
  deleteMany?:
    | Prisma.RegistrationSessionScalarWhereInput
    | Prisma.RegistrationSessionScalarWhereInput[]
}

export type RegistrationSessionUncheckedUpdateManyWithoutSessionNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.RegistrationSessionCreateWithoutSessionInput,
        Prisma.RegistrationSessionUncheckedCreateWithoutSessionInput
      >
    | Prisma.RegistrationSessionCreateWithoutSessionInput[]
    | Prisma.RegistrationSessionUncheckedCreateWithoutSessionInput[]
  connectOrCreate?:
    | Prisma.RegistrationSessionCreateOrConnectWithoutSessionInput
    | Prisma.RegistrationSessionCreateOrConnectWithoutSessionInput[]
  upsert?:
    | Prisma.RegistrationSessionUpsertWithWhereUniqueWithoutSessionInput
    | Prisma.RegistrationSessionUpsertWithWhereUniqueWithoutSessionInput[]
  createMany?: Prisma.RegistrationSessionCreateManySessionInputEnvelope
  set?:
    | Prisma.RegistrationSessionWhereUniqueInput
    | Prisma.RegistrationSessionWhereUniqueInput[]
  disconnect?:
    | Prisma.RegistrationSessionWhereUniqueInput
    | Prisma.RegistrationSessionWhereUniqueInput[]
  delete?:
    | Prisma.RegistrationSessionWhereUniqueInput
    | Prisma.RegistrationSessionWhereUniqueInput[]
  connect?:
    | Prisma.RegistrationSessionWhereUniqueInput
    | Prisma.RegistrationSessionWhereUniqueInput[]
  update?:
    | Prisma.RegistrationSessionUpdateWithWhereUniqueWithoutSessionInput
    | Prisma.RegistrationSessionUpdateWithWhereUniqueWithoutSessionInput[]
  updateMany?:
    | Prisma.RegistrationSessionUpdateManyWithWhereWithoutSessionInput
    | Prisma.RegistrationSessionUpdateManyWithWhereWithoutSessionInput[]
  deleteMany?:
    | Prisma.RegistrationSessionScalarWhereInput
    | Prisma.RegistrationSessionScalarWhereInput[]
}

export type RegistrationSessionCreateNestedManyWithoutRegistrationInput = {
  create?:
    | Prisma.XOR<
        Prisma.RegistrationSessionCreateWithoutRegistrationInput,
        Prisma.RegistrationSessionUncheckedCreateWithoutRegistrationInput
      >
    | Prisma.RegistrationSessionCreateWithoutRegistrationInput[]
    | Prisma.RegistrationSessionUncheckedCreateWithoutRegistrationInput[]
  connectOrCreate?:
    | Prisma.RegistrationSessionCreateOrConnectWithoutRegistrationInput
    | Prisma.RegistrationSessionCreateOrConnectWithoutRegistrationInput[]
  createMany?: Prisma.RegistrationSessionCreateManyRegistrationInputEnvelope
  connect?:
    | Prisma.RegistrationSessionWhereUniqueInput
    | Prisma.RegistrationSessionWhereUniqueInput[]
}

export type RegistrationSessionUncheckedCreateNestedManyWithoutRegistrationInput =
  {
    create?:
      | Prisma.XOR<
          Prisma.RegistrationSessionCreateWithoutRegistrationInput,
          Prisma.RegistrationSessionUncheckedCreateWithoutRegistrationInput
        >
      | Prisma.RegistrationSessionCreateWithoutRegistrationInput[]
      | Prisma.RegistrationSessionUncheckedCreateWithoutRegistrationInput[]
    connectOrCreate?:
      | Prisma.RegistrationSessionCreateOrConnectWithoutRegistrationInput
      | Prisma.RegistrationSessionCreateOrConnectWithoutRegistrationInput[]
    createMany?: Prisma.RegistrationSessionCreateManyRegistrationInputEnvelope
    connect?:
      | Prisma.RegistrationSessionWhereUniqueInput
      | Prisma.RegistrationSessionWhereUniqueInput[]
  }

export type RegistrationSessionUpdateManyWithoutRegistrationNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.RegistrationSessionCreateWithoutRegistrationInput,
        Prisma.RegistrationSessionUncheckedCreateWithoutRegistrationInput
      >
    | Prisma.RegistrationSessionCreateWithoutRegistrationInput[]
    | Prisma.RegistrationSessionUncheckedCreateWithoutRegistrationInput[]
  connectOrCreate?:
    | Prisma.RegistrationSessionCreateOrConnectWithoutRegistrationInput
    | Prisma.RegistrationSessionCreateOrConnectWithoutRegistrationInput[]
  upsert?:
    | Prisma.RegistrationSessionUpsertWithWhereUniqueWithoutRegistrationInput
    | Prisma.RegistrationSessionUpsertWithWhereUniqueWithoutRegistrationInput[]
  createMany?: Prisma.RegistrationSessionCreateManyRegistrationInputEnvelope
  set?:
    | Prisma.RegistrationSessionWhereUniqueInput
    | Prisma.RegistrationSessionWhereUniqueInput[]
  disconnect?:
    | Prisma.RegistrationSessionWhereUniqueInput
    | Prisma.RegistrationSessionWhereUniqueInput[]
  delete?:
    | Prisma.RegistrationSessionWhereUniqueInput
    | Prisma.RegistrationSessionWhereUniqueInput[]
  connect?:
    | Prisma.RegistrationSessionWhereUniqueInput
    | Prisma.RegistrationSessionWhereUniqueInput[]
  update?:
    | Prisma.RegistrationSessionUpdateWithWhereUniqueWithoutRegistrationInput
    | Prisma.RegistrationSessionUpdateWithWhereUniqueWithoutRegistrationInput[]
  updateMany?:
    | Prisma.RegistrationSessionUpdateManyWithWhereWithoutRegistrationInput
    | Prisma.RegistrationSessionUpdateManyWithWhereWithoutRegistrationInput[]
  deleteMany?:
    | Prisma.RegistrationSessionScalarWhereInput
    | Prisma.RegistrationSessionScalarWhereInput[]
}

export type RegistrationSessionUncheckedUpdateManyWithoutRegistrationNestedInput =
  {
    create?:
      | Prisma.XOR<
          Prisma.RegistrationSessionCreateWithoutRegistrationInput,
          Prisma.RegistrationSessionUncheckedCreateWithoutRegistrationInput
        >
      | Prisma.RegistrationSessionCreateWithoutRegistrationInput[]
      | Prisma.RegistrationSessionUncheckedCreateWithoutRegistrationInput[]
    connectOrCreate?:
      | Prisma.RegistrationSessionCreateOrConnectWithoutRegistrationInput
      | Prisma.RegistrationSessionCreateOrConnectWithoutRegistrationInput[]
    upsert?:
      | Prisma.RegistrationSessionUpsertWithWhereUniqueWithoutRegistrationInput
      | Prisma.RegistrationSessionUpsertWithWhereUniqueWithoutRegistrationInput[]
    createMany?: Prisma.RegistrationSessionCreateManyRegistrationInputEnvelope
    set?:
      | Prisma.RegistrationSessionWhereUniqueInput
      | Prisma.RegistrationSessionWhereUniqueInput[]
    disconnect?:
      | Prisma.RegistrationSessionWhereUniqueInput
      | Prisma.RegistrationSessionWhereUniqueInput[]
    delete?:
      | Prisma.RegistrationSessionWhereUniqueInput
      | Prisma.RegistrationSessionWhereUniqueInput[]
    connect?:
      | Prisma.RegistrationSessionWhereUniqueInput
      | Prisma.RegistrationSessionWhereUniqueInput[]
    update?:
      | Prisma.RegistrationSessionUpdateWithWhereUniqueWithoutRegistrationInput
      | Prisma.RegistrationSessionUpdateWithWhereUniqueWithoutRegistrationInput[]
    updateMany?:
      | Prisma.RegistrationSessionUpdateManyWithWhereWithoutRegistrationInput
      | Prisma.RegistrationSessionUpdateManyWithWhereWithoutRegistrationInput[]
    deleteMany?:
      | Prisma.RegistrationSessionScalarWhereInput
      | Prisma.RegistrationSessionScalarWhereInput[]
  }

export type RegistrationSessionCreateWithoutSessionInput = {
  id: string
  createdAt?: Date | string
  updatedAt?: Date | string
  registration: Prisma.RegistrationCreateNestedOneWithoutRegistrationSessionsInput
}

export type RegistrationSessionUncheckedCreateWithoutSessionInput = {
  id: string
  registrationId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type RegistrationSessionCreateOrConnectWithoutSessionInput = {
  where: Prisma.RegistrationSessionWhereUniqueInput
  create: Prisma.XOR<
    Prisma.RegistrationSessionCreateWithoutSessionInput,
    Prisma.RegistrationSessionUncheckedCreateWithoutSessionInput
  >
}

export type RegistrationSessionCreateManySessionInputEnvelope = {
  data:
    | Prisma.RegistrationSessionCreateManySessionInput
    | Prisma.RegistrationSessionCreateManySessionInput[]
  skipDuplicates?: boolean
}

export type RegistrationSessionUpsertWithWhereUniqueWithoutSessionInput = {
  where: Prisma.RegistrationSessionWhereUniqueInput
  update: Prisma.XOR<
    Prisma.RegistrationSessionUpdateWithoutSessionInput,
    Prisma.RegistrationSessionUncheckedUpdateWithoutSessionInput
  >
  create: Prisma.XOR<
    Prisma.RegistrationSessionCreateWithoutSessionInput,
    Prisma.RegistrationSessionUncheckedCreateWithoutSessionInput
  >
}

export type RegistrationSessionUpdateWithWhereUniqueWithoutSessionInput = {
  where: Prisma.RegistrationSessionWhereUniqueInput
  data: Prisma.XOR<
    Prisma.RegistrationSessionUpdateWithoutSessionInput,
    Prisma.RegistrationSessionUncheckedUpdateWithoutSessionInput
  >
}

export type RegistrationSessionUpdateManyWithWhereWithoutSessionInput = {
  where: Prisma.RegistrationSessionScalarWhereInput
  data: Prisma.XOR<
    Prisma.RegistrationSessionUpdateManyMutationInput,
    Prisma.RegistrationSessionUncheckedUpdateManyWithoutSessionInput
  >
}

export type RegistrationSessionScalarWhereInput = {
  AND?:
    | Prisma.RegistrationSessionScalarWhereInput
    | Prisma.RegistrationSessionScalarWhereInput[]
  OR?: Prisma.RegistrationSessionScalarWhereInput[]
  NOT?:
    | Prisma.RegistrationSessionScalarWhereInput
    | Prisma.RegistrationSessionScalarWhereInput[]
  id?: Prisma.StringFilter<"RegistrationSession"> | string
  registrationId?: Prisma.StringFilter<"RegistrationSession"> | string
  sessionId?: Prisma.StringFilter<"RegistrationSession"> | string
  createdAt?: Prisma.DateTimeFilter<"RegistrationSession"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"RegistrationSession"> | Date | string
}

export type RegistrationSessionCreateWithoutRegistrationInput = {
  id: string
  createdAt?: Date | string
  updatedAt?: Date | string
  session: Prisma.SessionCreateNestedOneWithoutRegistrationSessionsInput
}

export type RegistrationSessionUncheckedCreateWithoutRegistrationInput = {
  id: string
  sessionId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type RegistrationSessionCreateOrConnectWithoutRegistrationInput = {
  where: Prisma.RegistrationSessionWhereUniqueInput
  create: Prisma.XOR<
    Prisma.RegistrationSessionCreateWithoutRegistrationInput,
    Prisma.RegistrationSessionUncheckedCreateWithoutRegistrationInput
  >
}

export type RegistrationSessionCreateManyRegistrationInputEnvelope = {
  data:
    | Prisma.RegistrationSessionCreateManyRegistrationInput
    | Prisma.RegistrationSessionCreateManyRegistrationInput[]
  skipDuplicates?: boolean
}

export type RegistrationSessionUpsertWithWhereUniqueWithoutRegistrationInput = {
  where: Prisma.RegistrationSessionWhereUniqueInput
  update: Prisma.XOR<
    Prisma.RegistrationSessionUpdateWithoutRegistrationInput,
    Prisma.RegistrationSessionUncheckedUpdateWithoutRegistrationInput
  >
  create: Prisma.XOR<
    Prisma.RegistrationSessionCreateWithoutRegistrationInput,
    Prisma.RegistrationSessionUncheckedCreateWithoutRegistrationInput
  >
}

export type RegistrationSessionUpdateWithWhereUniqueWithoutRegistrationInput = {
  where: Prisma.RegistrationSessionWhereUniqueInput
  data: Prisma.XOR<
    Prisma.RegistrationSessionUpdateWithoutRegistrationInput,
    Prisma.RegistrationSessionUncheckedUpdateWithoutRegistrationInput
  >
}

export type RegistrationSessionUpdateManyWithWhereWithoutRegistrationInput = {
  where: Prisma.RegistrationSessionScalarWhereInput
  data: Prisma.XOR<
    Prisma.RegistrationSessionUpdateManyMutationInput,
    Prisma.RegistrationSessionUncheckedUpdateManyWithoutRegistrationInput
  >
}

export type RegistrationSessionCreateManySessionInput = {
  id: string
  registrationId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type RegistrationSessionUpdateWithoutSessionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  registration?: Prisma.RegistrationUpdateOneRequiredWithoutRegistrationSessionsNestedInput
}

export type RegistrationSessionUncheckedUpdateWithoutSessionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  registrationId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RegistrationSessionUncheckedUpdateManyWithoutSessionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  registrationId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RegistrationSessionCreateManyRegistrationInput = {
  id: string
  sessionId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type RegistrationSessionUpdateWithoutRegistrationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  session?: Prisma.SessionUpdateOneRequiredWithoutRegistrationSessionsNestedInput
}

export type RegistrationSessionUncheckedUpdateWithoutRegistrationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sessionId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RegistrationSessionUncheckedUpdateManyWithoutRegistrationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sessionId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RegistrationSessionSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean
    registrationId?: boolean
    sessionId?: boolean
    createdAt?: boolean
    updatedAt?: boolean
    registration?: boolean | Prisma.RegistrationDefaultArgs<ExtArgs>
    session?: boolean | Prisma.SessionDefaultArgs<ExtArgs>
  },
  ExtArgs["result"]["registrationSession"]
>

export type RegistrationSessionSelectCreateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean
    registrationId?: boolean
    sessionId?: boolean
    createdAt?: boolean
    updatedAt?: boolean
    registration?: boolean | Prisma.RegistrationDefaultArgs<ExtArgs>
    session?: boolean | Prisma.SessionDefaultArgs<ExtArgs>
  },
  ExtArgs["result"]["registrationSession"]
>

export type RegistrationSessionSelectUpdateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean
    registrationId?: boolean
    sessionId?: boolean
    createdAt?: boolean
    updatedAt?: boolean
    registration?: boolean | Prisma.RegistrationDefaultArgs<ExtArgs>
    session?: boolean | Prisma.SessionDefaultArgs<ExtArgs>
  },
  ExtArgs["result"]["registrationSession"]
>

export type RegistrationSessionSelectScalar = {
  id?: boolean
  registrationId?: boolean
  sessionId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type RegistrationSessionOmit<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<
  "id" | "registrationId" | "sessionId" | "createdAt" | "updatedAt",
  ExtArgs["result"]["registrationSession"]
>
export type RegistrationSessionInclude<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  registration?: boolean | Prisma.RegistrationDefaultArgs<ExtArgs>
  session?: boolean | Prisma.SessionDefaultArgs<ExtArgs>
}
export type RegistrationSessionIncludeCreateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  registration?: boolean | Prisma.RegistrationDefaultArgs<ExtArgs>
  session?: boolean | Prisma.SessionDefaultArgs<ExtArgs>
}
export type RegistrationSessionIncludeUpdateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  registration?: boolean | Prisma.RegistrationDefaultArgs<ExtArgs>
  session?: boolean | Prisma.SessionDefaultArgs<ExtArgs>
}

export type $RegistrationSessionPayload<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  name: "RegistrationSession"
  objects: {
    registration: Prisma.$RegistrationPayload<ExtArgs>
    session: Prisma.$SessionPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<
    {
      id: string
      registrationId: string
      sessionId: string
      createdAt: Date
      updatedAt: Date
    },
    ExtArgs["result"]["registrationSession"]
  >
  composites: {}
}

export type RegistrationSessionGetPayload<
  S extends boolean | null | undefined | RegistrationSessionDefaultArgs,
> = runtime.Types.Result.GetResult<Prisma.$RegistrationSessionPayload, S>

export type RegistrationSessionCountArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = Omit<
  RegistrationSessionFindManyArgs,
  "select" | "include" | "distinct" | "omit"
> & {
  select?: RegistrationSessionCountAggregateInputType | true
}

export interface RegistrationSessionDelegate<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> {
  [K: symbol]: {
    types: Prisma.TypeMap<ExtArgs>["model"]["RegistrationSession"]
    meta: { name: "RegistrationSession" }
  }
  /**
   * Find zero or one RegistrationSession that matches the filter.
   * @param {RegistrationSessionFindUniqueArgs} args - Arguments to find a RegistrationSession
   * @example
   * // Get one RegistrationSession
   * const registrationSession = await prisma.registrationSession.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends RegistrationSessionFindUniqueArgs>(
    args: Prisma.SelectSubset<T, RegistrationSessionFindUniqueArgs<ExtArgs>>
  ): Prisma.Prisma__RegistrationSessionClient<
    runtime.Types.Result.GetResult<
      Prisma.$RegistrationSessionPayload<ExtArgs>,
      T,
      "findUnique",
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find one RegistrationSession that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {RegistrationSessionFindUniqueOrThrowArgs} args - Arguments to find a RegistrationSession
   * @example
   * // Get one RegistrationSession
   * const registrationSession = await prisma.registrationSession.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends RegistrationSessionFindUniqueOrThrowArgs>(
    args: Prisma.SelectSubset<
      T,
      RegistrationSessionFindUniqueOrThrowArgs<ExtArgs>
    >
  ): Prisma.Prisma__RegistrationSessionClient<
    runtime.Types.Result.GetResult<
      Prisma.$RegistrationSessionPayload<ExtArgs>,
      T,
      "findUniqueOrThrow",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find the first RegistrationSession that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RegistrationSessionFindFirstArgs} args - Arguments to find a RegistrationSession
   * @example
   * // Get one RegistrationSession
   * const registrationSession = await prisma.registrationSession.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends RegistrationSessionFindFirstArgs>(
    args?: Prisma.SelectSubset<T, RegistrationSessionFindFirstArgs<ExtArgs>>
  ): Prisma.Prisma__RegistrationSessionClient<
    runtime.Types.Result.GetResult<
      Prisma.$RegistrationSessionPayload<ExtArgs>,
      T,
      "findFirst",
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find the first RegistrationSession that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RegistrationSessionFindFirstOrThrowArgs} args - Arguments to find a RegistrationSession
   * @example
   * // Get one RegistrationSession
   * const registrationSession = await prisma.registrationSession.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends RegistrationSessionFindFirstOrThrowArgs>(
    args?: Prisma.SelectSubset<
      T,
      RegistrationSessionFindFirstOrThrowArgs<ExtArgs>
    >
  ): Prisma.Prisma__RegistrationSessionClient<
    runtime.Types.Result.GetResult<
      Prisma.$RegistrationSessionPayload<ExtArgs>,
      T,
      "findFirstOrThrow",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find zero or more RegistrationSessions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RegistrationSessionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all RegistrationSessions
   * const registrationSessions = await prisma.registrationSession.findMany()
   *
   * // Get first 10 RegistrationSessions
   * const registrationSessions = await prisma.registrationSession.findMany({ take: 10 })
   *
   * // Only select the `id`
   * const registrationSessionWithIdOnly = await prisma.registrationSession.findMany({ select: { id: true } })
   *
   */
  findMany<T extends RegistrationSessionFindManyArgs>(
    args?: Prisma.SelectSubset<T, RegistrationSessionFindManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$RegistrationSessionPayload<ExtArgs>,
      T,
      "findMany",
      GlobalOmitOptions
    >
  >

  /**
   * Create a RegistrationSession.
   * @param {RegistrationSessionCreateArgs} args - Arguments to create a RegistrationSession.
   * @example
   * // Create one RegistrationSession
   * const RegistrationSession = await prisma.registrationSession.create({
   *   data: {
   *     // ... data to create a RegistrationSession
   *   }
   * })
   *
   */
  create<T extends RegistrationSessionCreateArgs>(
    args: Prisma.SelectSubset<T, RegistrationSessionCreateArgs<ExtArgs>>
  ): Prisma.Prisma__RegistrationSessionClient<
    runtime.Types.Result.GetResult<
      Prisma.$RegistrationSessionPayload<ExtArgs>,
      T,
      "create",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Create many RegistrationSessions.
   * @param {RegistrationSessionCreateManyArgs} args - Arguments to create many RegistrationSessions.
   * @example
   * // Create many RegistrationSessions
   * const registrationSession = await prisma.registrationSession.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   */
  createMany<T extends RegistrationSessionCreateManyArgs>(
    args?: Prisma.SelectSubset<T, RegistrationSessionCreateManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many RegistrationSessions and returns the data saved in the database.
   * @param {RegistrationSessionCreateManyAndReturnArgs} args - Arguments to create many RegistrationSessions.
   * @example
   * // Create many RegistrationSessions
   * const registrationSession = await prisma.registrationSession.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Create many RegistrationSessions and only return the `id`
   * const registrationSessionWithIdOnly = await prisma.registrationSession.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  createManyAndReturn<T extends RegistrationSessionCreateManyAndReturnArgs>(
    args?: Prisma.SelectSubset<
      T,
      RegistrationSessionCreateManyAndReturnArgs<ExtArgs>
    >
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$RegistrationSessionPayload<ExtArgs>,
      T,
      "createManyAndReturn",
      GlobalOmitOptions
    >
  >

  /**
   * Delete a RegistrationSession.
   * @param {RegistrationSessionDeleteArgs} args - Arguments to delete one RegistrationSession.
   * @example
   * // Delete one RegistrationSession
   * const RegistrationSession = await prisma.registrationSession.delete({
   *   where: {
   *     // ... filter to delete one RegistrationSession
   *   }
   * })
   *
   */
  delete<T extends RegistrationSessionDeleteArgs>(
    args: Prisma.SelectSubset<T, RegistrationSessionDeleteArgs<ExtArgs>>
  ): Prisma.Prisma__RegistrationSessionClient<
    runtime.Types.Result.GetResult<
      Prisma.$RegistrationSessionPayload<ExtArgs>,
      T,
      "delete",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Update one RegistrationSession.
   * @param {RegistrationSessionUpdateArgs} args - Arguments to update one RegistrationSession.
   * @example
   * // Update one RegistrationSession
   * const registrationSession = await prisma.registrationSession.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  update<T extends RegistrationSessionUpdateArgs>(
    args: Prisma.SelectSubset<T, RegistrationSessionUpdateArgs<ExtArgs>>
  ): Prisma.Prisma__RegistrationSessionClient<
    runtime.Types.Result.GetResult<
      Prisma.$RegistrationSessionPayload<ExtArgs>,
      T,
      "update",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Delete zero or more RegistrationSessions.
   * @param {RegistrationSessionDeleteManyArgs} args - Arguments to filter RegistrationSessions to delete.
   * @example
   * // Delete a few RegistrationSessions
   * const { count } = await prisma.registrationSession.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   *
   */
  deleteMany<T extends RegistrationSessionDeleteManyArgs>(
    args?: Prisma.SelectSubset<T, RegistrationSessionDeleteManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more RegistrationSessions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RegistrationSessionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many RegistrationSessions
   * const registrationSession = await prisma.registrationSession.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  updateMany<T extends RegistrationSessionUpdateManyArgs>(
    args: Prisma.SelectSubset<T, RegistrationSessionUpdateManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more RegistrationSessions and returns the data updated in the database.
   * @param {RegistrationSessionUpdateManyAndReturnArgs} args - Arguments to update many RegistrationSessions.
   * @example
   * // Update many RegistrationSessions
   * const registrationSession = await prisma.registrationSession.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Update zero or more RegistrationSessions and only return the `id`
   * const registrationSessionWithIdOnly = await prisma.registrationSession.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  updateManyAndReturn<T extends RegistrationSessionUpdateManyAndReturnArgs>(
    args: Prisma.SelectSubset<
      T,
      RegistrationSessionUpdateManyAndReturnArgs<ExtArgs>
    >
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$RegistrationSessionPayload<ExtArgs>,
      T,
      "updateManyAndReturn",
      GlobalOmitOptions
    >
  >

  /**
   * Create or update one RegistrationSession.
   * @param {RegistrationSessionUpsertArgs} args - Arguments to update or create a RegistrationSession.
   * @example
   * // Update or create a RegistrationSession
   * const registrationSession = await prisma.registrationSession.upsert({
   *   create: {
   *     // ... data to create a RegistrationSession
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the RegistrationSession we want to update
   *   }
   * })
   */
  upsert<T extends RegistrationSessionUpsertArgs>(
    args: Prisma.SelectSubset<T, RegistrationSessionUpsertArgs<ExtArgs>>
  ): Prisma.Prisma__RegistrationSessionClient<
    runtime.Types.Result.GetResult<
      Prisma.$RegistrationSessionPayload<ExtArgs>,
      T,
      "upsert",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Count the number of RegistrationSessions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RegistrationSessionCountArgs} args - Arguments to filter RegistrationSessions to count.
   * @example
   * // Count the number of RegistrationSessions
   * const count = await prisma.registrationSession.count({
   *   where: {
   *     // ... the filter for the RegistrationSessions we want to count
   *   }
   * })
   **/
  count<T extends RegistrationSessionCountArgs>(
    args?: Prisma.Subset<T, RegistrationSessionCountArgs>
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<"select", any>
      ? T["select"] extends true
        ? number
        : Prisma.GetScalarType<
            T["select"],
            RegistrationSessionCountAggregateOutputType
          >
      : number
  >

  /**
   * Allows you to perform aggregations operations on a RegistrationSession.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RegistrationSessionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
   **/
  aggregate<T extends RegistrationSessionAggregateArgs>(
    args: Prisma.Subset<T, RegistrationSessionAggregateArgs>
  ): Prisma.PrismaPromise<GetRegistrationSessionAggregateType<T>>

  /**
   * Group by RegistrationSession.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RegistrationSessionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   *
   **/
  groupBy<
    T extends RegistrationSessionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<"skip", Prisma.Keys<T>>,
      Prisma.Extends<"take", Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: RegistrationSessionGroupByArgs["orderBy"] }
      : { orderBy?: RegistrationSessionGroupByArgs["orderBy"] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<
      Prisma.Keys<Prisma.MaybeTupleToUnion<T["orderBy"]>>
    >,
    ByFields extends Prisma.MaybeTupleToUnion<T["by"]>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T["having"]>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T["by"] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
      ? `Error: "by" must not be empty.`
      : HavingValid extends Prisma.False
        ? {
            [P in HavingFields]: P extends ByFields
              ? never
              : P extends string
                ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                : [
                    Error,
                    "Field ",
                    P,
                    ` in "having" needs to be provided in "by"`,
                  ]
          }[HavingFields]
        : "take" extends Prisma.Keys<T>
          ? "orderBy" extends Prisma.Keys<T>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                }[OrderFields]
            : 'Error: If you provide "take", you also need to provide "orderBy"'
          : "skip" extends Prisma.Keys<T>
            ? "orderBy" extends Prisma.Keys<T>
              ? ByValid extends Prisma.True
                ? {}
                : {
                    [P in OrderFields]: P extends ByFields
                      ? never
                      : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                  }[OrderFields]
              : 'Error: If you provide "skip", you also need to provide "orderBy"'
            : ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                }[OrderFields],
  >(
    args: Prisma.SubsetIntersection<
      T,
      RegistrationSessionGroupByArgs,
      OrderByArg
    > &
      InputErrors
  ): {} extends InputErrors
    ? GetRegistrationSessionGroupByPayload<T>
    : Prisma.PrismaPromise<InputErrors>
  /**
   * Fields of the RegistrationSession model
   */
  readonly fields: RegistrationSessionFieldRefs
}

/**
 * The delegate class that acts as a "Promise-like" for RegistrationSession.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__RegistrationSessionClient<
  T,
  Null = never,
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  registration<T extends Prisma.RegistrationDefaultArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.RegistrationDefaultArgs<ExtArgs>>
  ): Prisma.Prisma__RegistrationClient<
    | runtime.Types.Result.GetResult<
        Prisma.$RegistrationPayload<ExtArgs>,
        T,
        "findUniqueOrThrow",
        GlobalOmitOptions
      >
    | Null,
    Null,
    ExtArgs,
    GlobalOmitOptions
  >
  session<T extends Prisma.SessionDefaultArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.SessionDefaultArgs<ExtArgs>>
  ): Prisma.Prisma__SessionClient<
    | runtime.Types.Result.GetResult<
        Prisma.$SessionPayload<ExtArgs>,
        T,
        "findUniqueOrThrow",
        GlobalOmitOptions
      >
    | Null,
    Null,
    ExtArgs,
    GlobalOmitOptions
  >
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(
    onfulfilled?:
      | ((value: T) => TResult1 | PromiseLike<TResult1>)
      | undefined
      | null,
    onrejected?:
      | ((reason: any) => TResult2 | PromiseLike<TResult2>)
      | undefined
      | null
  ): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(
    onrejected?:
      | ((reason: any) => TResult | PromiseLike<TResult>)
      | undefined
      | null
  ): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(
    onfinally?: (() => void) | undefined | null
  ): runtime.Types.Utils.JsPromise<T>
}

/**
 * Fields of the RegistrationSession model
 */
export interface RegistrationSessionFieldRefs {
  readonly id: Prisma.FieldRef<"RegistrationSession", "String">
  readonly registrationId: Prisma.FieldRef<"RegistrationSession", "String">
  readonly sessionId: Prisma.FieldRef<"RegistrationSession", "String">
  readonly createdAt: Prisma.FieldRef<"RegistrationSession", "DateTime">
  readonly updatedAt: Prisma.FieldRef<"RegistrationSession", "DateTime">
}

// Custom InputTypes
/**
 * RegistrationSession findUnique
 */
export type RegistrationSessionFindUniqueArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the RegistrationSession
   */
  select?: Prisma.RegistrationSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RegistrationSession
   */
  omit?: Prisma.RegistrationSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RegistrationSessionInclude<ExtArgs> | null
  /**
   * Filter, which RegistrationSession to fetch.
   */
  where: Prisma.RegistrationSessionWhereUniqueInput
}

/**
 * RegistrationSession findUniqueOrThrow
 */
export type RegistrationSessionFindUniqueOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the RegistrationSession
   */
  select?: Prisma.RegistrationSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RegistrationSession
   */
  omit?: Prisma.RegistrationSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RegistrationSessionInclude<ExtArgs> | null
  /**
   * Filter, which RegistrationSession to fetch.
   */
  where: Prisma.RegistrationSessionWhereUniqueInput
}

/**
 * RegistrationSession findFirst
 */
export type RegistrationSessionFindFirstArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the RegistrationSession
   */
  select?: Prisma.RegistrationSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RegistrationSession
   */
  omit?: Prisma.RegistrationSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RegistrationSessionInclude<ExtArgs> | null
  /**
   * Filter, which RegistrationSession to fetch.
   */
  where?: Prisma.RegistrationSessionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of RegistrationSessions to fetch.
   */
  orderBy?:
    | Prisma.RegistrationSessionOrderByWithRelationInput
    | Prisma.RegistrationSessionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for RegistrationSessions.
   */
  cursor?: Prisma.RegistrationSessionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` RegistrationSessions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` RegistrationSessions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of RegistrationSessions.
   */
  distinct?:
    | Prisma.RegistrationSessionScalarFieldEnum
    | Prisma.RegistrationSessionScalarFieldEnum[]
}

/**
 * RegistrationSession findFirstOrThrow
 */
export type RegistrationSessionFindFirstOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the RegistrationSession
   */
  select?: Prisma.RegistrationSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RegistrationSession
   */
  omit?: Prisma.RegistrationSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RegistrationSessionInclude<ExtArgs> | null
  /**
   * Filter, which RegistrationSession to fetch.
   */
  where?: Prisma.RegistrationSessionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of RegistrationSessions to fetch.
   */
  orderBy?:
    | Prisma.RegistrationSessionOrderByWithRelationInput
    | Prisma.RegistrationSessionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for RegistrationSessions.
   */
  cursor?: Prisma.RegistrationSessionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` RegistrationSessions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` RegistrationSessions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of RegistrationSessions.
   */
  distinct?:
    | Prisma.RegistrationSessionScalarFieldEnum
    | Prisma.RegistrationSessionScalarFieldEnum[]
}

/**
 * RegistrationSession findMany
 */
export type RegistrationSessionFindManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the RegistrationSession
   */
  select?: Prisma.RegistrationSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RegistrationSession
   */
  omit?: Prisma.RegistrationSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RegistrationSessionInclude<ExtArgs> | null
  /**
   * Filter, which RegistrationSessions to fetch.
   */
  where?: Prisma.RegistrationSessionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of RegistrationSessions to fetch.
   */
  orderBy?:
    | Prisma.RegistrationSessionOrderByWithRelationInput
    | Prisma.RegistrationSessionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for listing RegistrationSessions.
   */
  cursor?: Prisma.RegistrationSessionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` RegistrationSessions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` RegistrationSessions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of RegistrationSessions.
   */
  distinct?:
    | Prisma.RegistrationSessionScalarFieldEnum
    | Prisma.RegistrationSessionScalarFieldEnum[]
}

/**
 * RegistrationSession create
 */
export type RegistrationSessionCreateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the RegistrationSession
   */
  select?: Prisma.RegistrationSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RegistrationSession
   */
  omit?: Prisma.RegistrationSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RegistrationSessionInclude<ExtArgs> | null
  /**
   * The data needed to create a RegistrationSession.
   */
  data: Prisma.XOR<
    Prisma.RegistrationSessionCreateInput,
    Prisma.RegistrationSessionUncheckedCreateInput
  >
}

/**
 * RegistrationSession createMany
 */
export type RegistrationSessionCreateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to create many RegistrationSessions.
   */
  data:
    | Prisma.RegistrationSessionCreateManyInput
    | Prisma.RegistrationSessionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * RegistrationSession createManyAndReturn
 */
export type RegistrationSessionCreateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the RegistrationSession
   */
  select?: Prisma.RegistrationSessionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the RegistrationSession
   */
  omit?: Prisma.RegistrationSessionOmit<ExtArgs> | null
  /**
   * The data used to create many RegistrationSessions.
   */
  data:
    | Prisma.RegistrationSessionCreateManyInput
    | Prisma.RegistrationSessionCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RegistrationSessionIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * RegistrationSession update
 */
export type RegistrationSessionUpdateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the RegistrationSession
   */
  select?: Prisma.RegistrationSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RegistrationSession
   */
  omit?: Prisma.RegistrationSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RegistrationSessionInclude<ExtArgs> | null
  /**
   * The data needed to update a RegistrationSession.
   */
  data: Prisma.XOR<
    Prisma.RegistrationSessionUpdateInput,
    Prisma.RegistrationSessionUncheckedUpdateInput
  >
  /**
   * Choose, which RegistrationSession to update.
   */
  where: Prisma.RegistrationSessionWhereUniqueInput
}

/**
 * RegistrationSession updateMany
 */
export type RegistrationSessionUpdateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to update RegistrationSessions.
   */
  data: Prisma.XOR<
    Prisma.RegistrationSessionUpdateManyMutationInput,
    Prisma.RegistrationSessionUncheckedUpdateManyInput
  >
  /**
   * Filter which RegistrationSessions to update
   */
  where?: Prisma.RegistrationSessionWhereInput
  /**
   * Limit how many RegistrationSessions to update.
   */
  limit?: number
}

/**
 * RegistrationSession updateManyAndReturn
 */
export type RegistrationSessionUpdateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the RegistrationSession
   */
  select?: Prisma.RegistrationSessionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the RegistrationSession
   */
  omit?: Prisma.RegistrationSessionOmit<ExtArgs> | null
  /**
   * The data used to update RegistrationSessions.
   */
  data: Prisma.XOR<
    Prisma.RegistrationSessionUpdateManyMutationInput,
    Prisma.RegistrationSessionUncheckedUpdateManyInput
  >
  /**
   * Filter which RegistrationSessions to update
   */
  where?: Prisma.RegistrationSessionWhereInput
  /**
   * Limit how many RegistrationSessions to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RegistrationSessionIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * RegistrationSession upsert
 */
export type RegistrationSessionUpsertArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the RegistrationSession
   */
  select?: Prisma.RegistrationSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RegistrationSession
   */
  omit?: Prisma.RegistrationSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RegistrationSessionInclude<ExtArgs> | null
  /**
   * The filter to search for the RegistrationSession to update in case it exists.
   */
  where: Prisma.RegistrationSessionWhereUniqueInput
  /**
   * In case the RegistrationSession found by the `where` argument doesn't exist, create a new RegistrationSession with this data.
   */
  create: Prisma.XOR<
    Prisma.RegistrationSessionCreateInput,
    Prisma.RegistrationSessionUncheckedCreateInput
  >
  /**
   * In case the RegistrationSession was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<
    Prisma.RegistrationSessionUpdateInput,
    Prisma.RegistrationSessionUncheckedUpdateInput
  >
}

/**
 * RegistrationSession delete
 */
export type RegistrationSessionDeleteArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the RegistrationSession
   */
  select?: Prisma.RegistrationSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RegistrationSession
   */
  omit?: Prisma.RegistrationSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RegistrationSessionInclude<ExtArgs> | null
  /**
   * Filter which RegistrationSession to delete.
   */
  where: Prisma.RegistrationSessionWhereUniqueInput
}

/**
 * RegistrationSession deleteMany
 */
export type RegistrationSessionDeleteManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which RegistrationSessions to delete
   */
  where?: Prisma.RegistrationSessionWhereInput
  /**
   * Limit how many RegistrationSessions to delete.
   */
  limit?: number
}

/**
 * RegistrationSession without action
 */
export type RegistrationSessionDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the RegistrationSession
   */
  select?: Prisma.RegistrationSessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RegistrationSession
   */
  omit?: Prisma.RegistrationSessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RegistrationSessionInclude<ExtArgs> | null
}
