/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `UserOAuth` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model UserOAuth
 *
 */
export type UserOAuthModel =
  runtime.Types.Result.DefaultSelection<Prisma.$UserOAuthPayload>

export type AggregateUserOAuth = {
  _count: UserOAuthCountAggregateOutputType | null
  _min: UserOAuthMinAggregateOutputType | null
  _max: UserOAuthMaxAggregateOutputType | null
}

export type UserOAuthMinAggregateOutputType = {
  id: string | null
  oauthId: string | null
  userId: string | null
  provider: $Enums.OAuthProviderType | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type UserOAuthMaxAggregateOutputType = {
  id: string | null
  oauthId: string | null
  userId: string | null
  provider: $Enums.OAuthProviderType | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type UserOAuthCountAggregateOutputType = {
  id: number
  oauthId: number
  userId: number
  provider: number
  createdAt: number
  updatedAt: number
  _all: number
}

export type UserOAuthMinAggregateInputType = {
  id?: true
  oauthId?: true
  userId?: true
  provider?: true
  createdAt?: true
  updatedAt?: true
}

export type UserOAuthMaxAggregateInputType = {
  id?: true
  oauthId?: true
  userId?: true
  provider?: true
  createdAt?: true
  updatedAt?: true
}

export type UserOAuthCountAggregateInputType = {
  id?: true
  oauthId?: true
  userId?: true
  provider?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type UserOAuthAggregateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which UserOAuth to aggregate.
   */
  where?: Prisma.UserOAuthWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of UserOAuths to fetch.
   */
  orderBy?:
    | Prisma.UserOAuthOrderByWithRelationInput
    | Prisma.UserOAuthOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the start position
   */
  cursor?: Prisma.UserOAuthWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` UserOAuths from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` UserOAuths.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Count returned UserOAuths
   **/
  _count?: true | UserOAuthCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the minimum value
   **/
  _min?: UserOAuthMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the maximum value
   **/
  _max?: UserOAuthMaxAggregateInputType
}

export type GetUserOAuthAggregateType<T extends UserOAuthAggregateArgs> = {
  [P in keyof T & keyof AggregateUserOAuth]: P extends "_count" | "count"
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUserOAuth[P]>
    : Prisma.GetScalarType<T[P], AggregateUserOAuth[P]>
}

export type UserOAuthGroupByArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.UserOAuthWhereInput
  orderBy?:
    | Prisma.UserOAuthOrderByWithAggregationInput
    | Prisma.UserOAuthOrderByWithAggregationInput[]
  by: Prisma.UserOAuthScalarFieldEnum[] | Prisma.UserOAuthScalarFieldEnum
  having?: Prisma.UserOAuthScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UserOAuthCountAggregateInputType | true
  _min?: UserOAuthMinAggregateInputType
  _max?: UserOAuthMaxAggregateInputType
}

export type UserOAuthGroupByOutputType = {
  id: string
  oauthId: string
  userId: string
  provider: $Enums.OAuthProviderType
  createdAt: Date
  updatedAt: Date
  _count: UserOAuthCountAggregateOutputType | null
  _min: UserOAuthMinAggregateOutputType | null
  _max: UserOAuthMaxAggregateOutputType | null
}

export type GetUserOAuthGroupByPayload<T extends UserOAuthGroupByArgs> =
  Prisma.PrismaPromise<
    Array<
      Prisma.PickEnumerable<UserOAuthGroupByOutputType, T["by"]> & {
        [P in keyof T & keyof UserOAuthGroupByOutputType]: P extends "_count"
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UserOAuthGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UserOAuthGroupByOutputType[P]>
      }
    >
  >

export type UserOAuthWhereInput = {
  AND?: Prisma.UserOAuthWhereInput | Prisma.UserOAuthWhereInput[]
  OR?: Prisma.UserOAuthWhereInput[]
  NOT?: Prisma.UserOAuthWhereInput | Prisma.UserOAuthWhereInput[]
  id?: Prisma.StringFilter<"UserOAuth"> | string
  oauthId?: Prisma.StringFilter<"UserOAuth"> | string
  userId?: Prisma.StringFilter<"UserOAuth"> | string
  provider?:
    | Prisma.EnumOAuthProviderTypeFilter<"UserOAuth">
    | $Enums.OAuthProviderType
  createdAt?: Prisma.DateTimeFilter<"UserOAuth"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"UserOAuth"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type UserOAuthOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  oauthId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
}

export type UserOAuthWhereUniqueInput = Prisma.AtLeast<
  {
    id?: string
    oauthId?: string
    userId_provider?: Prisma.UserOAuthUserIdProviderCompoundUniqueInput
    AND?: Prisma.UserOAuthWhereInput | Prisma.UserOAuthWhereInput[]
    OR?: Prisma.UserOAuthWhereInput[]
    NOT?: Prisma.UserOAuthWhereInput | Prisma.UserOAuthWhereInput[]
    userId?: Prisma.StringFilter<"UserOAuth"> | string
    provider?:
      | Prisma.EnumOAuthProviderTypeFilter<"UserOAuth">
      | $Enums.OAuthProviderType
    createdAt?: Prisma.DateTimeFilter<"UserOAuth"> | Date | string
    updatedAt?: Prisma.DateTimeFilter<"UserOAuth"> | Date | string
    user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  },
  "id" | "oauthId" | "userId_provider"
>

export type UserOAuthOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  oauthId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.UserOAuthCountOrderByAggregateInput
  _max?: Prisma.UserOAuthMaxOrderByAggregateInput
  _min?: Prisma.UserOAuthMinOrderByAggregateInput
}

export type UserOAuthScalarWhereWithAggregatesInput = {
  AND?:
    | Prisma.UserOAuthScalarWhereWithAggregatesInput
    | Prisma.UserOAuthScalarWhereWithAggregatesInput[]
  OR?: Prisma.UserOAuthScalarWhereWithAggregatesInput[]
  NOT?:
    | Prisma.UserOAuthScalarWhereWithAggregatesInput
    | Prisma.UserOAuthScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"UserOAuth"> | string
  oauthId?: Prisma.StringWithAggregatesFilter<"UserOAuth"> | string
  userId?: Prisma.StringWithAggregatesFilter<"UserOAuth"> | string
  provider?:
    | Prisma.EnumOAuthProviderTypeWithAggregatesFilter<"UserOAuth">
    | $Enums.OAuthProviderType
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"UserOAuth"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"UserOAuth"> | Date | string
}

export type UserOAuthCreateInput = {
  id: string
  oauthId: string
  provider: $Enums.OAuthProviderType
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutUserOAuthsInput
}

export type UserOAuthUncheckedCreateInput = {
  id: string
  oauthId: string
  userId: string
  provider: $Enums.OAuthProviderType
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type UserOAuthUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  oauthId?: Prisma.StringFieldUpdateOperationsInput | string
  provider?:
    | Prisma.EnumOAuthProviderTypeFieldUpdateOperationsInput
    | $Enums.OAuthProviderType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutUserOAuthsNestedInput
}

export type UserOAuthUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  oauthId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  provider?:
    | Prisma.EnumOAuthProviderTypeFieldUpdateOperationsInput
    | $Enums.OAuthProviderType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserOAuthCreateManyInput = {
  id: string
  oauthId: string
  userId: string
  provider: $Enums.OAuthProviderType
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type UserOAuthUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  oauthId?: Prisma.StringFieldUpdateOperationsInput | string
  provider?:
    | Prisma.EnumOAuthProviderTypeFieldUpdateOperationsInput
    | $Enums.OAuthProviderType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserOAuthUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  oauthId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  provider?:
    | Prisma.EnumOAuthProviderTypeFieldUpdateOperationsInput
    | $Enums.OAuthProviderType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserOAuthListRelationFilter = {
  every?: Prisma.UserOAuthWhereInput
  some?: Prisma.UserOAuthWhereInput
  none?: Prisma.UserOAuthWhereInput
}

export type UserOAuthOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type UserOAuthUserIdProviderCompoundUniqueInput = {
  userId: string
  provider: $Enums.OAuthProviderType
}

export type UserOAuthCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  oauthId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type UserOAuthMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  oauthId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type UserOAuthMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  oauthId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type UserOAuthCreateNestedManyWithoutUserInput = {
  create?:
    | Prisma.XOR<
        Prisma.UserOAuthCreateWithoutUserInput,
        Prisma.UserOAuthUncheckedCreateWithoutUserInput
      >
    | Prisma.UserOAuthCreateWithoutUserInput[]
    | Prisma.UserOAuthUncheckedCreateWithoutUserInput[]
  connectOrCreate?:
    | Prisma.UserOAuthCreateOrConnectWithoutUserInput
    | Prisma.UserOAuthCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.UserOAuthCreateManyUserInputEnvelope
  connect?:
    | Prisma.UserOAuthWhereUniqueInput
    | Prisma.UserOAuthWhereUniqueInput[]
}

export type UserOAuthUncheckedCreateNestedManyWithoutUserInput = {
  create?:
    | Prisma.XOR<
        Prisma.UserOAuthCreateWithoutUserInput,
        Prisma.UserOAuthUncheckedCreateWithoutUserInput
      >
    | Prisma.UserOAuthCreateWithoutUserInput[]
    | Prisma.UserOAuthUncheckedCreateWithoutUserInput[]
  connectOrCreate?:
    | Prisma.UserOAuthCreateOrConnectWithoutUserInput
    | Prisma.UserOAuthCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.UserOAuthCreateManyUserInputEnvelope
  connect?:
    | Prisma.UserOAuthWhereUniqueInput
    | Prisma.UserOAuthWhereUniqueInput[]
}

export type UserOAuthUpdateManyWithoutUserNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.UserOAuthCreateWithoutUserInput,
        Prisma.UserOAuthUncheckedCreateWithoutUserInput
      >
    | Prisma.UserOAuthCreateWithoutUserInput[]
    | Prisma.UserOAuthUncheckedCreateWithoutUserInput[]
  connectOrCreate?:
    | Prisma.UserOAuthCreateOrConnectWithoutUserInput
    | Prisma.UserOAuthCreateOrConnectWithoutUserInput[]
  upsert?:
    | Prisma.UserOAuthUpsertWithWhereUniqueWithoutUserInput
    | Prisma.UserOAuthUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.UserOAuthCreateManyUserInputEnvelope
  set?: Prisma.UserOAuthWhereUniqueInput | Prisma.UserOAuthWhereUniqueInput[]
  disconnect?:
    | Prisma.UserOAuthWhereUniqueInput
    | Prisma.UserOAuthWhereUniqueInput[]
  delete?: Prisma.UserOAuthWhereUniqueInput | Prisma.UserOAuthWhereUniqueInput[]
  connect?:
    | Prisma.UserOAuthWhereUniqueInput
    | Prisma.UserOAuthWhereUniqueInput[]
  update?:
    | Prisma.UserOAuthUpdateWithWhereUniqueWithoutUserInput
    | Prisma.UserOAuthUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?:
    | Prisma.UserOAuthUpdateManyWithWhereWithoutUserInput
    | Prisma.UserOAuthUpdateManyWithWhereWithoutUserInput[]
  deleteMany?:
    | Prisma.UserOAuthScalarWhereInput
    | Prisma.UserOAuthScalarWhereInput[]
}

export type UserOAuthUncheckedUpdateManyWithoutUserNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.UserOAuthCreateWithoutUserInput,
        Prisma.UserOAuthUncheckedCreateWithoutUserInput
      >
    | Prisma.UserOAuthCreateWithoutUserInput[]
    | Prisma.UserOAuthUncheckedCreateWithoutUserInput[]
  connectOrCreate?:
    | Prisma.UserOAuthCreateOrConnectWithoutUserInput
    | Prisma.UserOAuthCreateOrConnectWithoutUserInput[]
  upsert?:
    | Prisma.UserOAuthUpsertWithWhereUniqueWithoutUserInput
    | Prisma.UserOAuthUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.UserOAuthCreateManyUserInputEnvelope
  set?: Prisma.UserOAuthWhereUniqueInput | Prisma.UserOAuthWhereUniqueInput[]
  disconnect?:
    | Prisma.UserOAuthWhereUniqueInput
    | Prisma.UserOAuthWhereUniqueInput[]
  delete?: Prisma.UserOAuthWhereUniqueInput | Prisma.UserOAuthWhereUniqueInput[]
  connect?:
    | Prisma.UserOAuthWhereUniqueInput
    | Prisma.UserOAuthWhereUniqueInput[]
  update?:
    | Prisma.UserOAuthUpdateWithWhereUniqueWithoutUserInput
    | Prisma.UserOAuthUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?:
    | Prisma.UserOAuthUpdateManyWithWhereWithoutUserInput
    | Prisma.UserOAuthUpdateManyWithWhereWithoutUserInput[]
  deleteMany?:
    | Prisma.UserOAuthScalarWhereInput
    | Prisma.UserOAuthScalarWhereInput[]
}

export type EnumOAuthProviderTypeFieldUpdateOperationsInput = {
  set?: $Enums.OAuthProviderType
}

export type UserOAuthCreateWithoutUserInput = {
  id: string
  oauthId: string
  provider: $Enums.OAuthProviderType
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type UserOAuthUncheckedCreateWithoutUserInput = {
  id: string
  oauthId: string
  provider: $Enums.OAuthProviderType
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type UserOAuthCreateOrConnectWithoutUserInput = {
  where: Prisma.UserOAuthWhereUniqueInput
  create: Prisma.XOR<
    Prisma.UserOAuthCreateWithoutUserInput,
    Prisma.UserOAuthUncheckedCreateWithoutUserInput
  >
}

export type UserOAuthCreateManyUserInputEnvelope = {
  data:
    | Prisma.UserOAuthCreateManyUserInput
    | Prisma.UserOAuthCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type UserOAuthUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.UserOAuthWhereUniqueInput
  update: Prisma.XOR<
    Prisma.UserOAuthUpdateWithoutUserInput,
    Prisma.UserOAuthUncheckedUpdateWithoutUserInput
  >
  create: Prisma.XOR<
    Prisma.UserOAuthCreateWithoutUserInput,
    Prisma.UserOAuthUncheckedCreateWithoutUserInput
  >
}

export type UserOAuthUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.UserOAuthWhereUniqueInput
  data: Prisma.XOR<
    Prisma.UserOAuthUpdateWithoutUserInput,
    Prisma.UserOAuthUncheckedUpdateWithoutUserInput
  >
}

export type UserOAuthUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.UserOAuthScalarWhereInput
  data: Prisma.XOR<
    Prisma.UserOAuthUpdateManyMutationInput,
    Prisma.UserOAuthUncheckedUpdateManyWithoutUserInput
  >
}

export type UserOAuthScalarWhereInput = {
  AND?: Prisma.UserOAuthScalarWhereInput | Prisma.UserOAuthScalarWhereInput[]
  OR?: Prisma.UserOAuthScalarWhereInput[]
  NOT?: Prisma.UserOAuthScalarWhereInput | Prisma.UserOAuthScalarWhereInput[]
  id?: Prisma.StringFilter<"UserOAuth"> | string
  oauthId?: Prisma.StringFilter<"UserOAuth"> | string
  userId?: Prisma.StringFilter<"UserOAuth"> | string
  provider?:
    | Prisma.EnumOAuthProviderTypeFilter<"UserOAuth">
    | $Enums.OAuthProviderType
  createdAt?: Prisma.DateTimeFilter<"UserOAuth"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"UserOAuth"> | Date | string
}

export type UserOAuthCreateManyUserInput = {
  id: string
  oauthId: string
  provider: $Enums.OAuthProviderType
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type UserOAuthUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  oauthId?: Prisma.StringFieldUpdateOperationsInput | string
  provider?:
    | Prisma.EnumOAuthProviderTypeFieldUpdateOperationsInput
    | $Enums.OAuthProviderType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserOAuthUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  oauthId?: Prisma.StringFieldUpdateOperationsInput | string
  provider?:
    | Prisma.EnumOAuthProviderTypeFieldUpdateOperationsInput
    | $Enums.OAuthProviderType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserOAuthUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  oauthId?: Prisma.StringFieldUpdateOperationsInput | string
  provider?:
    | Prisma.EnumOAuthProviderTypeFieldUpdateOperationsInput
    | $Enums.OAuthProviderType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserOAuthSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean
    oauthId?: boolean
    userId?: boolean
    provider?: boolean
    createdAt?: boolean
    updatedAt?: boolean
    user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  },
  ExtArgs["result"]["userOAuth"]
>

export type UserOAuthSelectCreateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean
    oauthId?: boolean
    userId?: boolean
    provider?: boolean
    createdAt?: boolean
    updatedAt?: boolean
    user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  },
  ExtArgs["result"]["userOAuth"]
>

export type UserOAuthSelectUpdateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean
    oauthId?: boolean
    userId?: boolean
    provider?: boolean
    createdAt?: boolean
    updatedAt?: boolean
    user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  },
  ExtArgs["result"]["userOAuth"]
>

export type UserOAuthSelectScalar = {
  id?: boolean
  oauthId?: boolean
  userId?: boolean
  provider?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type UserOAuthOmit<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<
  "id" | "oauthId" | "userId" | "provider" | "createdAt" | "updatedAt",
  ExtArgs["result"]["userOAuth"]
>
export type UserOAuthInclude<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type UserOAuthIncludeCreateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type UserOAuthIncludeUpdateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $UserOAuthPayload<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  name: "UserOAuth"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<
    {
      id: string
      oauthId: string
      userId: string
      provider: $Enums.OAuthProviderType
      createdAt: Date
      updatedAt: Date
    },
    ExtArgs["result"]["userOAuth"]
  >
  composites: {}
}

export type UserOAuthGetPayload<
  S extends boolean | null | undefined | UserOAuthDefaultArgs,
> = runtime.Types.Result.GetResult<Prisma.$UserOAuthPayload, S>

export type UserOAuthCountArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = Omit<UserOAuthFindManyArgs, "select" | "include" | "distinct" | "omit"> & {
  select?: UserOAuthCountAggregateInputType | true
}

export interface UserOAuthDelegate<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> {
  [K: symbol]: {
    types: Prisma.TypeMap<ExtArgs>["model"]["UserOAuth"]
    meta: { name: "UserOAuth" }
  }
  /**
   * Find zero or one UserOAuth that matches the filter.
   * @param {UserOAuthFindUniqueArgs} args - Arguments to find a UserOAuth
   * @example
   * // Get one UserOAuth
   * const userOAuth = await prisma.userOAuth.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UserOAuthFindUniqueArgs>(
    args: Prisma.SelectSubset<T, UserOAuthFindUniqueArgs<ExtArgs>>
  ): Prisma.Prisma__UserOAuthClient<
    runtime.Types.Result.GetResult<
      Prisma.$UserOAuthPayload<ExtArgs>,
      T,
      "findUnique",
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find one UserOAuth that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UserOAuthFindUniqueOrThrowArgs} args - Arguments to find a UserOAuth
   * @example
   * // Get one UserOAuth
   * const userOAuth = await prisma.userOAuth.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UserOAuthFindUniqueOrThrowArgs>(
    args: Prisma.SelectSubset<T, UserOAuthFindUniqueOrThrowArgs<ExtArgs>>
  ): Prisma.Prisma__UserOAuthClient<
    runtime.Types.Result.GetResult<
      Prisma.$UserOAuthPayload<ExtArgs>,
      T,
      "findUniqueOrThrow",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find the first UserOAuth that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserOAuthFindFirstArgs} args - Arguments to find a UserOAuth
   * @example
   * // Get one UserOAuth
   * const userOAuth = await prisma.userOAuth.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UserOAuthFindFirstArgs>(
    args?: Prisma.SelectSubset<T, UserOAuthFindFirstArgs<ExtArgs>>
  ): Prisma.Prisma__UserOAuthClient<
    runtime.Types.Result.GetResult<
      Prisma.$UserOAuthPayload<ExtArgs>,
      T,
      "findFirst",
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find the first UserOAuth that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserOAuthFindFirstOrThrowArgs} args - Arguments to find a UserOAuth
   * @example
   * // Get one UserOAuth
   * const userOAuth = await prisma.userOAuth.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UserOAuthFindFirstOrThrowArgs>(
    args?: Prisma.SelectSubset<T, UserOAuthFindFirstOrThrowArgs<ExtArgs>>
  ): Prisma.Prisma__UserOAuthClient<
    runtime.Types.Result.GetResult<
      Prisma.$UserOAuthPayload<ExtArgs>,
      T,
      "findFirstOrThrow",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find zero or more UserOAuths that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserOAuthFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all UserOAuths
   * const userOAuths = await prisma.userOAuth.findMany()
   *
   * // Get first 10 UserOAuths
   * const userOAuths = await prisma.userOAuth.findMany({ take: 10 })
   *
   * // Only select the `id`
   * const userOAuthWithIdOnly = await prisma.userOAuth.findMany({ select: { id: true } })
   *
   */
  findMany<T extends UserOAuthFindManyArgs>(
    args?: Prisma.SelectSubset<T, UserOAuthFindManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$UserOAuthPayload<ExtArgs>,
      T,
      "findMany",
      GlobalOmitOptions
    >
  >

  /**
   * Create a UserOAuth.
   * @param {UserOAuthCreateArgs} args - Arguments to create a UserOAuth.
   * @example
   * // Create one UserOAuth
   * const UserOAuth = await prisma.userOAuth.create({
   *   data: {
   *     // ... data to create a UserOAuth
   *   }
   * })
   *
   */
  create<T extends UserOAuthCreateArgs>(
    args: Prisma.SelectSubset<T, UserOAuthCreateArgs<ExtArgs>>
  ): Prisma.Prisma__UserOAuthClient<
    runtime.Types.Result.GetResult<
      Prisma.$UserOAuthPayload<ExtArgs>,
      T,
      "create",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Create many UserOAuths.
   * @param {UserOAuthCreateManyArgs} args - Arguments to create many UserOAuths.
   * @example
   * // Create many UserOAuths
   * const userOAuth = await prisma.userOAuth.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   */
  createMany<T extends UserOAuthCreateManyArgs>(
    args?: Prisma.SelectSubset<T, UserOAuthCreateManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many UserOAuths and returns the data saved in the database.
   * @param {UserOAuthCreateManyAndReturnArgs} args - Arguments to create many UserOAuths.
   * @example
   * // Create many UserOAuths
   * const userOAuth = await prisma.userOAuth.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Create many UserOAuths and only return the `id`
   * const userOAuthWithIdOnly = await prisma.userOAuth.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  createManyAndReturn<T extends UserOAuthCreateManyAndReturnArgs>(
    args?: Prisma.SelectSubset<T, UserOAuthCreateManyAndReturnArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$UserOAuthPayload<ExtArgs>,
      T,
      "createManyAndReturn",
      GlobalOmitOptions
    >
  >

  /**
   * Delete a UserOAuth.
   * @param {UserOAuthDeleteArgs} args - Arguments to delete one UserOAuth.
   * @example
   * // Delete one UserOAuth
   * const UserOAuth = await prisma.userOAuth.delete({
   *   where: {
   *     // ... filter to delete one UserOAuth
   *   }
   * })
   *
   */
  delete<T extends UserOAuthDeleteArgs>(
    args: Prisma.SelectSubset<T, UserOAuthDeleteArgs<ExtArgs>>
  ): Prisma.Prisma__UserOAuthClient<
    runtime.Types.Result.GetResult<
      Prisma.$UserOAuthPayload<ExtArgs>,
      T,
      "delete",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Update one UserOAuth.
   * @param {UserOAuthUpdateArgs} args - Arguments to update one UserOAuth.
   * @example
   * // Update one UserOAuth
   * const userOAuth = await prisma.userOAuth.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  update<T extends UserOAuthUpdateArgs>(
    args: Prisma.SelectSubset<T, UserOAuthUpdateArgs<ExtArgs>>
  ): Prisma.Prisma__UserOAuthClient<
    runtime.Types.Result.GetResult<
      Prisma.$UserOAuthPayload<ExtArgs>,
      T,
      "update",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Delete zero or more UserOAuths.
   * @param {UserOAuthDeleteManyArgs} args - Arguments to filter UserOAuths to delete.
   * @example
   * // Delete a few UserOAuths
   * const { count } = await prisma.userOAuth.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   *
   */
  deleteMany<T extends UserOAuthDeleteManyArgs>(
    args?: Prisma.SelectSubset<T, UserOAuthDeleteManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserOAuths.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserOAuthUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many UserOAuths
   * const userOAuth = await prisma.userOAuth.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  updateMany<T extends UserOAuthUpdateManyArgs>(
    args: Prisma.SelectSubset<T, UserOAuthUpdateManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserOAuths and returns the data updated in the database.
   * @param {UserOAuthUpdateManyAndReturnArgs} args - Arguments to update many UserOAuths.
   * @example
   * // Update many UserOAuths
   * const userOAuth = await prisma.userOAuth.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Update zero or more UserOAuths and only return the `id`
   * const userOAuthWithIdOnly = await prisma.userOAuth.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  updateManyAndReturn<T extends UserOAuthUpdateManyAndReturnArgs>(
    args: Prisma.SelectSubset<T, UserOAuthUpdateManyAndReturnArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$UserOAuthPayload<ExtArgs>,
      T,
      "updateManyAndReturn",
      GlobalOmitOptions
    >
  >

  /**
   * Create or update one UserOAuth.
   * @param {UserOAuthUpsertArgs} args - Arguments to update or create a UserOAuth.
   * @example
   * // Update or create a UserOAuth
   * const userOAuth = await prisma.userOAuth.upsert({
   *   create: {
   *     // ... data to create a UserOAuth
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the UserOAuth we want to update
   *   }
   * })
   */
  upsert<T extends UserOAuthUpsertArgs>(
    args: Prisma.SelectSubset<T, UserOAuthUpsertArgs<ExtArgs>>
  ): Prisma.Prisma__UserOAuthClient<
    runtime.Types.Result.GetResult<
      Prisma.$UserOAuthPayload<ExtArgs>,
      T,
      "upsert",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Count the number of UserOAuths.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserOAuthCountArgs} args - Arguments to filter UserOAuths to count.
   * @example
   * // Count the number of UserOAuths
   * const count = await prisma.userOAuth.count({
   *   where: {
   *     // ... the filter for the UserOAuths we want to count
   *   }
   * })
   **/
  count<T extends UserOAuthCountArgs>(
    args?: Prisma.Subset<T, UserOAuthCountArgs>
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<"select", any>
      ? T["select"] extends true
        ? number
        : Prisma.GetScalarType<T["select"], UserOAuthCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a UserOAuth.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserOAuthAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
   **/
  aggregate<T extends UserOAuthAggregateArgs>(
    args: Prisma.Subset<T, UserOAuthAggregateArgs>
  ): Prisma.PrismaPromise<GetUserOAuthAggregateType<T>>

  /**
   * Group by UserOAuth.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserOAuthGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   *
   **/
  groupBy<
    T extends UserOAuthGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<"skip", Prisma.Keys<T>>,
      Prisma.Extends<"take", Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UserOAuthGroupByArgs["orderBy"] }
      : { orderBy?: UserOAuthGroupByArgs["orderBy"] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<
      Prisma.Keys<Prisma.MaybeTupleToUnion<T["orderBy"]>>
    >,
    ByFields extends Prisma.MaybeTupleToUnion<T["by"]>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T["having"]>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T["by"] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
      ? `Error: "by" must not be empty.`
      : HavingValid extends Prisma.False
        ? {
            [P in HavingFields]: P extends ByFields
              ? never
              : P extends string
                ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                : [
                    Error,
                    "Field ",
                    P,
                    ` in "having" needs to be provided in "by"`,
                  ]
          }[HavingFields]
        : "take" extends Prisma.Keys<T>
          ? "orderBy" extends Prisma.Keys<T>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                }[OrderFields]
            : 'Error: If you provide "take", you also need to provide "orderBy"'
          : "skip" extends Prisma.Keys<T>
            ? "orderBy" extends Prisma.Keys<T>
              ? ByValid extends Prisma.True
                ? {}
                : {
                    [P in OrderFields]: P extends ByFields
                      ? never
                      : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                  }[OrderFields]
              : 'Error: If you provide "skip", you also need to provide "orderBy"'
            : ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                }[OrderFields],
  >(
    args: Prisma.SubsetIntersection<T, UserOAuthGroupByArgs, OrderByArg> &
      InputErrors
  ): {} extends InputErrors
    ? GetUserOAuthGroupByPayload<T>
    : Prisma.PrismaPromise<InputErrors>
  /**
   * Fields of the UserOAuth model
   */
  readonly fields: UserOAuthFieldRefs
}

/**
 * The delegate class that acts as a "Promise-like" for UserOAuth.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UserOAuthClient<
  T,
  Null = never,
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>
  ): Prisma.Prisma__UserClient<
    | runtime.Types.Result.GetResult<
        Prisma.$UserPayload<ExtArgs>,
        T,
        "findUniqueOrThrow",
        GlobalOmitOptions
      >
    | Null,
    Null,
    ExtArgs,
    GlobalOmitOptions
  >
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(
    onfulfilled?:
      | ((value: T) => TResult1 | PromiseLike<TResult1>)
      | undefined
      | null,
    onrejected?:
      | ((reason: any) => TResult2 | PromiseLike<TResult2>)
      | undefined
      | null
  ): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(
    onrejected?:
      | ((reason: any) => TResult | PromiseLike<TResult>)
      | undefined
      | null
  ): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(
    onfinally?: (() => void) | undefined | null
  ): runtime.Types.Utils.JsPromise<T>
}

/**
 * Fields of the UserOAuth model
 */
export interface UserOAuthFieldRefs {
  readonly id: Prisma.FieldRef<"UserOAuth", "String">
  readonly oauthId: Prisma.FieldRef<"UserOAuth", "String">
  readonly userId: Prisma.FieldRef<"UserOAuth", "String">
  readonly provider: Prisma.FieldRef<"UserOAuth", "OAuthProviderType">
  readonly createdAt: Prisma.FieldRef<"UserOAuth", "DateTime">
  readonly updatedAt: Prisma.FieldRef<"UserOAuth", "DateTime">
}

// Custom InputTypes
/**
 * UserOAuth findUnique
 */
export type UserOAuthFindUniqueArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the UserOAuth
   */
  select?: Prisma.UserOAuthSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserOAuth
   */
  omit?: Prisma.UserOAuthOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserOAuthInclude<ExtArgs> | null
  /**
   * Filter, which UserOAuth to fetch.
   */
  where: Prisma.UserOAuthWhereUniqueInput
}

/**
 * UserOAuth findUniqueOrThrow
 */
export type UserOAuthFindUniqueOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the UserOAuth
   */
  select?: Prisma.UserOAuthSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserOAuth
   */
  omit?: Prisma.UserOAuthOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserOAuthInclude<ExtArgs> | null
  /**
   * Filter, which UserOAuth to fetch.
   */
  where: Prisma.UserOAuthWhereUniqueInput
}

/**
 * UserOAuth findFirst
 */
export type UserOAuthFindFirstArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the UserOAuth
   */
  select?: Prisma.UserOAuthSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserOAuth
   */
  omit?: Prisma.UserOAuthOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserOAuthInclude<ExtArgs> | null
  /**
   * Filter, which UserOAuth to fetch.
   */
  where?: Prisma.UserOAuthWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of UserOAuths to fetch.
   */
  orderBy?:
    | Prisma.UserOAuthOrderByWithRelationInput
    | Prisma.UserOAuthOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for UserOAuths.
   */
  cursor?: Prisma.UserOAuthWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` UserOAuths from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` UserOAuths.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of UserOAuths.
   */
  distinct?: Prisma.UserOAuthScalarFieldEnum | Prisma.UserOAuthScalarFieldEnum[]
}

/**
 * UserOAuth findFirstOrThrow
 */
export type UserOAuthFindFirstOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the UserOAuth
   */
  select?: Prisma.UserOAuthSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserOAuth
   */
  omit?: Prisma.UserOAuthOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserOAuthInclude<ExtArgs> | null
  /**
   * Filter, which UserOAuth to fetch.
   */
  where?: Prisma.UserOAuthWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of UserOAuths to fetch.
   */
  orderBy?:
    | Prisma.UserOAuthOrderByWithRelationInput
    | Prisma.UserOAuthOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for UserOAuths.
   */
  cursor?: Prisma.UserOAuthWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` UserOAuths from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` UserOAuths.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of UserOAuths.
   */
  distinct?: Prisma.UserOAuthScalarFieldEnum | Prisma.UserOAuthScalarFieldEnum[]
}

/**
 * UserOAuth findMany
 */
export type UserOAuthFindManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the UserOAuth
   */
  select?: Prisma.UserOAuthSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserOAuth
   */
  omit?: Prisma.UserOAuthOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserOAuthInclude<ExtArgs> | null
  /**
   * Filter, which UserOAuths to fetch.
   */
  where?: Prisma.UserOAuthWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of UserOAuths to fetch.
   */
  orderBy?:
    | Prisma.UserOAuthOrderByWithRelationInput
    | Prisma.UserOAuthOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for listing UserOAuths.
   */
  cursor?: Prisma.UserOAuthWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` UserOAuths from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` UserOAuths.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of UserOAuths.
   */
  distinct?: Prisma.UserOAuthScalarFieldEnum | Prisma.UserOAuthScalarFieldEnum[]
}

/**
 * UserOAuth create
 */
export type UserOAuthCreateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the UserOAuth
   */
  select?: Prisma.UserOAuthSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserOAuth
   */
  omit?: Prisma.UserOAuthOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserOAuthInclude<ExtArgs> | null
  /**
   * The data needed to create a UserOAuth.
   */
  data: Prisma.XOR<
    Prisma.UserOAuthCreateInput,
    Prisma.UserOAuthUncheckedCreateInput
  >
}

/**
 * UserOAuth createMany
 */
export type UserOAuthCreateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to create many UserOAuths.
   */
  data: Prisma.UserOAuthCreateManyInput | Prisma.UserOAuthCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * UserOAuth createManyAndReturn
 */
export type UserOAuthCreateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the UserOAuth
   */
  select?: Prisma.UserOAuthSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserOAuth
   */
  omit?: Prisma.UserOAuthOmit<ExtArgs> | null
  /**
   * The data used to create many UserOAuths.
   */
  data: Prisma.UserOAuthCreateManyInput | Prisma.UserOAuthCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserOAuthIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * UserOAuth update
 */
export type UserOAuthUpdateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the UserOAuth
   */
  select?: Prisma.UserOAuthSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserOAuth
   */
  omit?: Prisma.UserOAuthOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserOAuthInclude<ExtArgs> | null
  /**
   * The data needed to update a UserOAuth.
   */
  data: Prisma.XOR<
    Prisma.UserOAuthUpdateInput,
    Prisma.UserOAuthUncheckedUpdateInput
  >
  /**
   * Choose, which UserOAuth to update.
   */
  where: Prisma.UserOAuthWhereUniqueInput
}

/**
 * UserOAuth updateMany
 */
export type UserOAuthUpdateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to update UserOAuths.
   */
  data: Prisma.XOR<
    Prisma.UserOAuthUpdateManyMutationInput,
    Prisma.UserOAuthUncheckedUpdateManyInput
  >
  /**
   * Filter which UserOAuths to update
   */
  where?: Prisma.UserOAuthWhereInput
  /**
   * Limit how many UserOAuths to update.
   */
  limit?: number
}

/**
 * UserOAuth updateManyAndReturn
 */
export type UserOAuthUpdateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the UserOAuth
   */
  select?: Prisma.UserOAuthSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserOAuth
   */
  omit?: Prisma.UserOAuthOmit<ExtArgs> | null
  /**
   * The data used to update UserOAuths.
   */
  data: Prisma.XOR<
    Prisma.UserOAuthUpdateManyMutationInput,
    Prisma.UserOAuthUncheckedUpdateManyInput
  >
  /**
   * Filter which UserOAuths to update
   */
  where?: Prisma.UserOAuthWhereInput
  /**
   * Limit how many UserOAuths to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserOAuthIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * UserOAuth upsert
 */
export type UserOAuthUpsertArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the UserOAuth
   */
  select?: Prisma.UserOAuthSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserOAuth
   */
  omit?: Prisma.UserOAuthOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserOAuthInclude<ExtArgs> | null
  /**
   * The filter to search for the UserOAuth to update in case it exists.
   */
  where: Prisma.UserOAuthWhereUniqueInput
  /**
   * In case the UserOAuth found by the `where` argument doesn't exist, create a new UserOAuth with this data.
   */
  create: Prisma.XOR<
    Prisma.UserOAuthCreateInput,
    Prisma.UserOAuthUncheckedCreateInput
  >
  /**
   * In case the UserOAuth was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<
    Prisma.UserOAuthUpdateInput,
    Prisma.UserOAuthUncheckedUpdateInput
  >
}

/**
 * UserOAuth delete
 */
export type UserOAuthDeleteArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the UserOAuth
   */
  select?: Prisma.UserOAuthSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserOAuth
   */
  omit?: Prisma.UserOAuthOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserOAuthInclude<ExtArgs> | null
  /**
   * Filter which UserOAuth to delete.
   */
  where: Prisma.UserOAuthWhereUniqueInput
}

/**
 * UserOAuth deleteMany
 */
export type UserOAuthDeleteManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which UserOAuths to delete
   */
  where?: Prisma.UserOAuthWhereInput
  /**
   * Limit how many UserOAuths to delete.
   */
  limit?: number
}

/**
 * UserOAuth without action
 */
export type UserOAuthDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the UserOAuth
   */
  select?: Prisma.UserOAuthSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserOAuth
   */
  omit?: Prisma.UserOAuthOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserOAuthInclude<ExtArgs> | null
}
